[package]
name = "installed-rs"
version = "0.1.0"
authors = ["chaixb <1481569358@qq.com>"]
edition = "2018"

[dependencies]
yansi = "0.5.0"
serde_json = "1.0.39"
serde = { version = "1.0.91", features= ["derive"] }
